# Generated by Django 4.2.16 on 2025-12-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("success", "Sucesso"),
                            ("warning", "Aviso"),
                            ("danger", "Importante"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_inicio", models.DateTimeField(auto_now_add=True)),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deixe em branco para não expirar",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Anúncio",
                "verbose_name_plural": "Anúncios",
                "ordering": ["-criado_em"],
            },
        ),
    ]
