# Generated by Django 4.2.7 on 2026-05-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_anuncio"),
    ]

    operations = [
        migrations.AddField(
            model_name="horarioatendimento",
            name="profissional",
            field=models.ForeignKey(
                blank=True,
                help_text="Deixe em branco para um horário geral da empresa",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios_atendimento",
                to="core.profissional",
            ),
        ),
    ]
