# Generated by Django 4.2.7 on 2026-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_horarioatendimento_profissional"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição curta da barbearia para exibir na página pública",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="foto_capa",
            field=models.ImageField(
                blank=True,
                help_text="Foto de capa da barbearia (banner da página pública)",
                null=True,
                upload_to="capas/",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo da barbearia (será exibida na página pública)",
                null=True,
                upload_to="logos/",
            ),
        ),
    ]
