# Generated by Django 4.2.7 on 2026-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_empresa_descricao_empresa_foto_capa_empresa_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Opcional", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="foto_capa",
            field=models.ImageField(
                blank=True,
                help_text="Legado: não é mais usado na página pública (apenas logo).",
                null=True,
                upload_to="capas/",
            ),
        ),
    ]
